import streamlit as st 


st.sidebar.markdown("Home Page")

st.markdown("# Welcome to the ESG Certification Recommender System!")

st.write(""" \
         This application aims to recommend environmental, sustainability, and governance (ESG) certifications \
         for IT products by comparing the compatibility of product attributes/features with certification \
         requirements. A data administrator can upload product data, create a data dictionary with column \
         definitions generated by LLMs, then search through products and see the compatibility with various \
         ESG certifications like TCO, Energy Star, and 80 Plus. \
         """)

st.divider()

st.caption("Created by Stibo Systems Project Team 2 (Jackson Duke, Sofia Laval, and Nathan Ruiz)")

